"""empty message

Revision ID: 6fba5faed8ba
Revises: f412961e4743
Create Date: 2020-12-10 21:30:07.862391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fba5faed8ba'
down_revision = 'f412961e4743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('list_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'list_id')
    # ### end Alembic commands ###
