"""empty message

Revision ID: f412961e4743
Revises: 938e704a99bc
Create Date: 2020-12-09 23:16:55.701320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f412961e4743'
down_revision = '938e704a99bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('super', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'super')
    # ### end Alembic commands ###
